### ISSUE TITLE
Fehler: group_indicator: verschwindet bei dynamischen background (Objekt)

### ISSUE THREAD

**Issue by ruhr70** [Pmant/ioBroker.vis-justgage#10]
wenn man für den CSS Hintergrund ein Objekt verwendet, z.B.{javascript.0.Schwellwerte.Klima.Temperatur.Bad.backgroundColor}

wird der Group-Indicator nur unregelmässig angezeigt. Er blitzt kurz auf und ist dann wieder weg.

[http://forum.iobroker.net/viewtopic.php?f=22&t=3139#p28753](http://forum.iobroker.net/viewtopic.php?f=22&t=3139#p28753)

**Comment by Pmant** [comment]
Das ist im Prinzip das selbe Problem wie bei #9 und hängt damit zusammen wie die dynamischen bindings umgesetzt sind. In diesem Fall wird so weit ich weiß das ganze Widget neu geladen, daher fehlt dann auch wieder der Indikator.

**Comment by ruhr70** [comment]
mit 0.4.3 umgesetzt. Danke!
