### ISSUE TITLE
Since version 1.0.1 the entry in property layout/color for gauge color will be ignored.

### ISSUE THREAD

**Issue by RK62** [Pmant/ioBroker.vis-justgage#26]
Since version 1.0.1 the entry in property layout/color 1 for gauge color will be ignored.
And there will be shown no color when enter a value in the property layout/color 2 or /color 3.

![image](https://user-images.githubusercontent.com/39200469/66674906-71b3bc00-ec64-11e9-99f3-b74a9833b7d8.png)

_Originally posted by @RK62 in https://github.com/Pmant/ioBroker.vis-justgage/pull/25#issuecomment-541171307_

**Comment by MK-66** [comment]
I have the same issues, see also my post in "Probleme mit min/mid/max Werten"

**Comment by MK-66** [comment]
New Version 1.0.2 is on latest repository and everything seems to be working fine with js-controller 2.0.39. Many thanks to the developers and many thanks also for the quick reaction!

**Comment by RK62** [comment]
Thanks, it's fixed in V1.0.2
