### ISSUE TITLE
replace pow with normal limit

### ISSUE THREAD

**Issue by GermanBluefox** [Pmant/ioBroker.vis-justgage#5]
Nobody can understand what the pow is. May be it would be better to replace pow with normal value? If widget it allows and it is not part of justgage.

**Comment by Pmant** [comment]
You don't have to use the pows at all, the gradient behaves linear if you don't enter any values (same like 1,1,1). For me this is important for my temperature widgets as I want them with min/max 15/30 but the gradient should turn blue and red faster than linear (and blue even more faster than red).

**Comment by Pmant** [comment]
figured out a more intuitive way to define the pows, please try 0.4.0

**Comment by Pmant** [comment]
published 0.4.9
